---
- name: Install formd into virtual environment
  pip: name='git+https://github.com/drbunsen/formd'
       editable=False
       virtualenv=/usr/local/env/formd
       virtualenv_command=virtualenv2

- name: Link formd to bin
  file: src=/usr/local/env/formd/bin/formd.py
        dest=/usr/local/bin/formd
        state=link
