---
- name: Install xdg stuff
  pacman: name={{ item }} state=present
  with_items:
    - xdg-user-dirs
    - xdg-utils
  tags:
    - xdg

- name: Create user directories
  command: /usr/bin/xdg-user-dirs-update
  become: yes
  become_user: "{{ user.name }}"
  tags:
    - xdg
