---
- name: Push mail sync script
  template: src=mailsync.sh.j2 dest=/usr/local/bin/mailsync mode=755
  tags:
    - mailsync

- name: Push mailsync service file
  template: src=mailsync.service.j2 dest=/etc/systemd/system/mailsync@.service
  tags:
    - mailsync
  notify:
    - reload systemd config

- name: Push mailsync timer file
  template: src=mailsync.timer.j2 dest=/etc/systemd/system/mailsync@.timer
  tags:
    - mailsync
  notify:
    - reload systemd config
    - restart mailsync

- name: Enable and start mailsync timer
  service: name="mailsync@{{ user.name }}.timer" enabled=yes state=started
  when: mail.sync_on == "all"
  tags:
    - mailsync

- name: Remove mailsync from trusted unit list
  lineinfile: dest=/usr/local/etc/trusted_units
              state=absent
              line="mailsync@{{ user.name }}.timer"
  when: mail.sync_on == "all"
  tags:
    - mailsync

- name: Disable mailsync timer
  service: name="mailsync@{{ user.name }}.timer" enabled=no
  when: mail.sync_on == "trusted"
  tags:
    - mailsync

- name: Add mailsync to trusted unit list
  lineinfile: dest=/usr/local/etc/trusted_units
              state=present
              line="mailsync@{{ user.name }}.timer"
  when: mail.sync_on == "trusted"
  tags:
    - mailsync
