---
- name: Install docker apps
  pacman: name={{ item }} state=present
  with_items:
    - docker
    - docker-compose

- name: Add myself to docker group
  user: name={{ user.name }} groups=docker append=yes
