---
- name: Copy pacman configuration file
  copy: src=pacman.conf dest=/etc/pacman.conf

- name: Refresh pacman mirrors
  pacman: update_cache=yes

- name: Set the hostname
  hostname: name={{ hostname }}
  when: hostname is defined

- include_tasks: shell.yml
- include_tasks: user.yml
- include_tasks: sudo.yml
- include_tasks: packages.yml
- include_tasks: journal.yml
