---
- name: Install PulseAudio
  pacman: name={{ item }} state=present
  with_items:
      - pulseaudio
      - pulseaudio-alsa
      - lib32-libpulse
      - lib32-alsa-plugins

- name: Switch output to newly connected devices
  lineinfile: dest=/etc/pulse/default.pa
              state=present
              line="load-module module-switch-on-connect"

- name: Install pulseaudio controls
  aur: name=pulseaudio-ctl user={{ user.name }}
  with_items:
    - pulseaudio-ctl
    - pulsemixer
  tags:
    - aur
